Travel/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('place/', views.place, name='place'),
    path('service/', views.service, name='service'),
    path('hotel/', views.hotel, name='hotel'),
    path('blog/', views.blog, name='blog'),
    path('contact/', views.contact, name='contact'),
]

main/models.py
from django.db import models


class Banner(models.Model):
    # =====class banner=========
    title = models.CharField(max_length=255)
    body = models.TextField()

    def __str__(self):
        return self.title
    

class Service(models.Model):
    # =====class service=========
    name = models.CharField(max_length=255)
    body = models.TextField()
    icon = models.FileField(upload_to='Services/')
    
    def __str__(self):
        return self.name
    

class AboutUs(models.Model):
    # =====class about=========
    title = models.CharField(max_length=255)
    body = models.TextField()

    def __str__(self):
        return self.body
    

class Place(models.Model):
    # =====class place=========
    image = models.FileField(upload_to='Places/')
    url = models.URLField()
    title = models.CharField(max_length=255)
    price = models.DecimalField(decimal_places=2, max_digits=10)
    body = models.TextField()
    how_long = models.TextField()
    where = models.TextField()

    def __str__(self):
        return self.title
    

class Blog(models.Model):
    # =====class blog=========
    image = models.FileField(upload_to='Blogs/')
    title = models.CharField(max_length=255)
    body = models.TextField()
    when = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=255)

    def __str__(self):
        return self.title
    

class Contact(models.Model):
    # =====class contact=========
    name = models.CharField(max_length=255)
    email = models.EmailField(blank=True, null=True)
    phone = models.CharField(max_length=255)
    body = models.TextField()
    is_show = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)


class Hotel(models.Model):
    # =====class hotel=========
    image = models.FileField(upload_to='Hotels/')
    title = models.CharField(max_length=255)
    price = models.DecimalField(decimal_places=2, max_digits=10)
    body = models.TextField()
    where = models.CharField(max_length=255)

    def __str__(self):
        return self.title
    

main/views.py
from django.shortcuts import render

from . import models

def index(request):
    """-----------Home page------------"""
    banner = models.Banner.objects.last()
    about = models.AboutUs.objects.last()
    services = models.Service.objects.all()
    places = models.Place.objects.all()
    hotels = models.Hotel.objects.all()
    blogs = models.Blog.objects.all()
    contacts = models.Contact.objects.all()
    context = {
        'banner':banner,
        'about':about,
        'places':places,
        'hotels':hotels,
        'blogs':blogs,
        'services':services,
        'contacts':contacts
    }
    return render(request, 'index.html', context)

def contact(request):
    """-----------contact-----------"""
    if request.method == 'POST':
        try:
            models.Contact.objects.create(
                name=request.POST['name'],
                email=request.POST['email'],
                phone=request.POST['phone'],
                body=request.POST['message']
            )
        except:
            ...
    return render(request, 'contact.html')


def service(request):
    """-----------service-----------"""
    services = models.Service.objects.all()

    context = {
        'services':services,    }
    return render(request, 'service.html', context)


def about(request):
    """-----------about-----------"""
    contacts = models.Contact.objects.all()
    places = models.Place.objects.all()
    hotels = models.Hotel.objects.all()
    about = models.AboutUs.objects.last()

    data = {
        'about':about,
        'places':places,
        'hotels':hotels,
        'contacts':contacts
    }
    return render(request, 'about.html', context=data)

def place(request):
    """-----------place-----------"""
    places = models.Place.objects.all()
    context = {
        'places':places,
    }
    return render(request, 'places.html', context)



def hotel(request):
    """-----------hotel-----------"""
    hotels = models.Hotel.objects.all()
    context = {
        'hotels':hotels,
    }
    return render(request, 'hotel.html', context)



def blog(request):
    """-----------blog-----------"""
    blogs = models.Blog.objects.all()
    context = {
        'blogs':blogs,
    }
    return render(request, 'blog.html', context)

templates/about.html
{% extends "base.html" %}
{% load static %}
{% block content  %}
    
    <div class="hero-wrap js-fullheight" style="background-image: url({% static 'images/bg_1.jpg' %});">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-center" data-scrollax-parent="true">
          <div class="col-md-9 text-center ftco-animate" data-scrollax=" properties: { translateY: '70%' }">
            <p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><span class="mr-2"><a href="{% url 'main:index' %}">Home</a></span> <span>About</span></p>
            <h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">Biz Haqimizda</h1>
          </div>
        </div>
      </div>
    </div>

    <section class="ftco-section">
    	<div class="container">
    		<div class="row">
    			<div class="col-md-4" style="display: flex; justify-content: center;">
    				<div class="intro">
    					<h3><span>01</span> Sayohat</h3>
    					<p>Biz sizni istalgan manzilingizga olib boramiz va Comfort zonani ta'minlaymiz.</p>
    				</div>
    			</div>
    			<div class="col-md-4">
    				<div class="intro">
    					<h3><span>02</span> Tajriba</h3>
    					<p>Bizda tajribali ishchilar ishlaydi Ular juda ko'p vaqtdan beri bu ish bilan ishlashadi.</p>
    				</div>
    			</div>
    			<div class="col-md-4">
    				<div class="intro">
    					<h3><span>03</span> Hordiq</h3>
    					<p>Biz sizni olib boradigan joylarda siz kutmagan narsalar bor: Atraktsionlar, Basseynlar va Boshqalar.</p>
    				</div>
    			</div>
    		</div>
    	</div>
    </section>


    <section class="ftco-section ftco-counter img" id="section-counter" style="background-image: url({% static 'images/bg_1.jpg' %});" data-stellar-background-ratio="0.5">
    	<div class="container">
    		<div class="row justify-content-center">
    			<div class="col-md-10">
		    		<div class="row" style="display: flex; justify-content: center;">
		          <div class="col-md-3 d-flex justify-content-center counter-wrap ftco-animate">
		            <div class="block-18 text-center">
		              <div class="text">
		                <strong class="number" data-number="{{contacts | length}}">0</strong>
		                <span>Mijozlar</span>
		              </div>
		            </div>
		          </div>
		          <div class="col-md-3 d-flex justify-content-center counter-wrap ftco-animate">
		            <div class="block-18 text-center">
		              <div class="text">
		                <strong class="number" data-number="{{places | length}}">0</strong>
		                <span>Mashhur Joylar</span>
		              </div>
		            </div>
		          </div>
		          <div class="col-md-3 d-flex justify-content-center counter-wrap ftco-animate">
		            <div class="block-18 text-center">
		              <div class="text">
		                <strong class="number" data-number="{{hotels | length}}">0</strong>
		                <span>Hotellar</span>
		              </div>
		            </div>
		          </div>
		        </div>
	        </div>
        </div>
    	</div>
    </section>
		
		<section class="ftco-about d-md-flex">
    	<div class="one-half img" style="background-image: url({% static 'images/about.jpg' %});"></div>
    	<div class="one-half ftco-animate">
        <div class="heading-section ftco-animate ">
          <h2 class="mb-4">{{about.title}}</h2>
        </div>
        <div>
  				<p>{{about.body}}.</p>
  			</div>
    	</div>
    </section>

    <section class="ftco-section testimony-section">
      <div class="container">
        <div class="row justify-content-center mb-5 pb-3">
          <div class="col-md-7 text-center heading-section heading-section-white ftco-animate">
            <h2 class="mb-4">Mijozlarning fikrlari</h2>
          </div>
        </div>
        <div class="row ftco-animate">
          <div class="col-md-12">
            <div class="carousel-testimony owl-carousel ftco-owl">
              {% for contact in contacts %}
              <div class="item">
                <div class="testimony-wrap p-4 pb-5">
                  <div class="user-img mb-5" style="background-image: url({% static 'images/person_1.jpg' %})">
                    <span class="quote d-flex align-items-center justify-content-center">
                      <i class="icon-quote-left"></i>
                    </span>
                  </div>
                  <div class="text">
                    <p class="name">{{contact.name}}</p>
                    <p class="mb-5">{{contact.body}}.</p>
                    <span class="position"></span>
                  </div>
                </div>
              </div>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </section>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <title>Turizm Uz</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Abril+Fatface" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">

    <link rel="stylesheet" href="{% static 'css/aos.css' %}">

    <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.timepicker.css' %}">

    
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
  <body>
    
	  <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
	    <div class="container">
	      <a class="navbar-brand" href="{% url 'main:index' %}">Adventure</a>
	      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="oi oi-menu"></span> Menu
	      </button>

	      <div class="collapse navbar-collapse" id="ftco-nav">
	        <ul class="navbar-nav ml-auto">
	          <li class="nav-item active"><a href="{% url 'main:index' %}" class="nav-link">Bosh Sahifa</a></li>
	          <li class="nav-item"><a href="{% url 'main:about' %}" class="nav-link">Biz Haqimizda</a></li>
	          <li class="nav-item"><a href="{% url 'main:place' %}" class="nav-link">Manzillar</a></li>
	          <li class="nav-item"><a href="{% url 'main:service' %}" class="nav-link">Servislar</a></li>
	          <li class="nav-item"><a href="{% url 'main:hotel' %}" class="nav-link">Hotellar</a></li>
	          <li class="nav-item"><a href="{% url 'main:blog' %}" class="nav-link">Blog</a></li>
	          <li class="nav-item"><a href="{% url 'main:contact' %}" class="nav-link">Kontakt</a></li>
	        </ul>
	      </div>
	    </div>
	  </nav>
    <!-- END nav -->
    {% block content %}
    {% endblock %}

      <footer class="ftco-footer ftco-bg-dark ftco-section">
        <div class="container">
          <div class="row mb-5">
            <div class="col-md">
              <div class="ftco-footer-widget mb-4">
                <h2 class="ftco-heading-2">Sayohat</h2>
                <p>Xohlagan davlatingizga borish imkonini beruvchi Sayt | Tezkor | Arzon | Sifatli | Ishonchli.</p>
                <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-3">
                  <li class="ftco-animate"><a href="#"><span class="icon-telegram"></span></a></li>
                  <li class="ftco-animate"><a href="#"><span class="icon-github"></span></a></li>
                  <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
                </ul>
              </div>
            </div>
            <div class="col-md">
              <div class="ftco-footer-widget mb-4 ml-md-4">
                <h2 class="ftco-heading-2">Ma'lumot</h2>
                <ul class="list-unstyled">
                  <li><a href="{% url 'main:about' %}" class="py-2 d-block">Biz Haqimizda</a></li>
                  <li><a href="{% url 'main:contact' %}" class="py-2 d-block">Contact</a></li>
                  <li><a href="{% url 'main:place' %}" class="py-2 d-block">Manzillar</a></li>
                  <li><a href="{% url 'main:blog' %}" class="py-2 d-block">Blog</a></li>
                  <li><a href="{% url 'main:service' %}" class="py-2 d-block">Servislar</a></li>
                </ul>
              </div>
            </div>
            <div class="col-md">
              <div class="ftco-footer-widget mb-4">
                  <h2 class="ftco-heading-2">Savollar bormi?</h2>
                  <div class="block-23 mb-3">
                    <ul>
                      <li><span class="icon icon-map-marker"></span><span class="text">O`zbekiton Farg`ona</span></li>
                      <li><a href="#"><span class="icon icon-phone"></span><span class="text">+998 99 999 99 99</span></a></li>
                      <li><a href="#"><span class="icon icon-envelope"></span><span class="text">Google.com</span></a></li>
                    </ul>
                  </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12 text-center">
  
              <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
              Copyright &copy;<script>document.write(new Date().getFullYear());</script> | All rights reserved by Aziz.dev |
              <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
            </div>
          </div>
        </div>
      </footer>
      
    
  
    <!-- loader -->
    <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>
  
  
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
    <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'js/jquery.stellar.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/aos.js' %}"></script>
    <script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
    <script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
    <script src="{% static 'js/scrollax.min.js' %}"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
    <script src="{% static 'js/main.js' %}"></script>
      
    </body>
</html>

templates/blog.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    
    <div class="hero-wrap js-fullheight" style="background-image: url({% static 'images/bg_1.jpg' %});">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-center" data-scrollax-parent="true">
          <div class="col-md-9 text-center ftco-animate" data-scrollax=" properties: { translateY: '70%' }">
            <p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><span class="mr-2"><a href="{% url 'main:index' %}">Bosh Sahifa</a></span> <span>Blog</span></p>
            <h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">Bloglar</h1>
          </div>
        </div>
      </div>
    </div>

    <section class="ftco-section bg-light">
      <div class="container">
        <div class="row d-flex">
          {% for blog in blogs %}
          <div class="col-md-4 d-flex ftco-animate">
            <div class="blog-entry align-self-stretch">
              <a href="blog-single.html" class="block-20" style="background-image: url({{blog.image.url}});">
              </a>
              <div class="text">
              	<span class="tag">{{blog.title}}</span>
                <h3 class="heading mt-3"><a href="">{{blog.body}}</a></h3>
                <div class="meta mb-3">
                  <div><a href="">{{blog.when}}</a></div>
                  <div><a href="">{{blog.author}}</a></div>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
        <div class="row mt-5">
          <div class="col text-center">
            <div class="block-27">
              <ul>
                <li><a href="#">&lt;</a></li>
                <li class="active"><span>1</span></li>
                <li><a href="#">&gt;</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </section>
{% endblock %}

templates/contact.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    
    <div class="hero-wrap js-fullheight" style="background-image: url({% static 'images/bg_1.jpg' %});">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-center" data-scrollax-parent="true">
          <div class="col-md-9 text-center ftco-animate" data-scrollax=" properties: { translateY: '70%' }">
            <p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><span class="mr-2"><a href="{% url 'main:index' %}">Bosh Sahifa</a></span> <span>Kontakt</span></p>
            <h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">Kontakt</h1>
          </div>
        </div>
      </div>
    </div>

    <section class="ftco-section contact-section ftco-degree-bg">
      <div class="container">
        <div class="row d-flex mb-5 contact-info">
          <div class="col-md-12 mb-4">
            <h2 class="h4">Biz bilan bog'lanish</h2>
          </div>
          <div class="w-100"></div>
          <div class="col-md-3">
            <p><span>Address:</span> Alisher Navai street, Fergana, Uzbekistan</p>
          </div>
          <div class="col-md-3">
            <p><span>Phone:</span> <a href="tel://+998999999999">+998 99 999 99 99</a></p>
          </div>
          <div class="col-md-3">
            <p><span>Email:</span> <a href="mailto:example@gmail.com">example@gmail.com</a></p>
          </div>
          <div class="col-md-3">
            <p><span>Website</span> <a href="">example.com</a></p>
          </div>
        </div>
        <div class="row block-5" style="display: flex; justify-content: center;">
          <div class="col-md-8 order-md-last pr-md-5">
            <form method="post">
              {% csrf_token %}
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Your Name" name="name">
              </div>
              <div class="form-group">
                <input type="email" class="form-control" placeholder="Your Email" name="email">
              </div>
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Phone" name="phone">
              </div>
              <div class="form-group">
                <textarea name="message" cols="30" rows="7" class="form-control" placeholder="Message" ></textarea>
              </div>
              <div class="form-group" style="display: flex; justify-content: center;">
                <input type="submit" value="Send Message" class="btn btn-outline-warning py-3 px-12">
              </div>
            </form>
          </div>
          </div>
        </div>
      </div>
    </section>

{% endblock %}

templates/hotel.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    
    <div class="hero-wrap js-fullheight" style="background-image: url({% static 'images/bg_1.jpg' %});">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-center" data-scrollax-parent="true">
          <div class="col-md-9 text-center ftco-animate" data-scrollax=" properties: { translateY: '70%' }">
            <p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><span class="mr-2"><a href="{% url 'main:index' %}">Bosh Sahifa</a></span> <span>Hotel</span></p>
            <h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">Hotellar</h1>
          </div>
        </div>
      </div>
    </div>
		
		<section class="ftco-section">
      <div class="container">
        <div class="row" style="display: flex; justify-content: center;">
        	<div class="col-lg-10 sidebar order-md-last ftco-animate">
        		<div class="sidebar-wrap ftco-animate">
        			<h3 class="heading mb-4 text-center" style="padding: 40px;"><b>Shaharni Topish</b></h3>
        			<form action="">
        				<div class="fields">
		              <div class="form-group">
		                <input type="text" class="form-control" placeholder="Manzil, Shaharlar">
		              </div>
		              <div class="form-group">
		                <div class="select-wrap one-third">
	                    <div class="icon"><span class="ion-ios-arrow-down"></span></div>
	                    <select name="" id="" class="form-control" placeholder="Keyword search">
	                      <option value="">Lokatsiya tanlash</option>
	                      <option value="">O`zbekiston</option>
	                      <option value="">Turkiya</option>
	                      <option value="">Amerika</option>
	                      <option value="">Rossiya</option>
	                    </select>
	                  </div>
		              </div>
		              <div class="form-group">
		                <input type="text" id="checkin_date" class="form-control checkin_date" placeholder="Kundan">
		              </div>
		              <div class="form-group">
		                <input type="text" id="checkout_date" class="form-control checkout_date" placeholder="Kungacha">
		              </div>
		              <div class="form-group">
		                <input type="submit" value="Qidirish" class="btn btn-outline-warning py-3 px-5">
		              </div>
		            </div>
	            </form>
        		</div>
        	</div><!-- END-->
        	<div class="col-lg-12">
          			<div class="row">
						{% for hotel in hotels %}
							<div class="col-sm col-md-6 col-lg-4 ftco-animate">
								<div class="destination">
									<a href="" class="img img-2 d-flex justify-content-center align-items-center" style="background-image: url({{hotel.image.url}});">
										<div class="icon d-flex justify-content-center align-items-center">
											<span class="icon-link"></span>
										</div>
									</a>
									<div class="text p-3">
										<div class="d-flex">
											<div class="one">
												<h3><a href="">{{hotel.title}}</a></h3>
												<p class="rate">
													<i class="icon-star"></i>
													<i class="icon-star"></i>
													<i class="icon-star"></i>
													<i class="icon-star"></i>
													<i class="icon-star-o"></i>
													<span>8 Rating</span>
												</p>
											</div>
											<div class="two">
												<span class="price per-price">${{hotel.price}}<br><small>/night</small></span>
											</div>
										</div>
										<p>{{hotel.body}}</p>
										<hr>
										<p class="bottom-area d-flex">
											<span><i class="icon-map-o"></i> {{hotel.where}}</span> 
											<span class="ml-auto"><a href="#">Book Now</a></span>
										</p>
									</div>
								</div>
							</div>
						{% endfor %}
		    		</div>
          			<div class="row mt-5">
						<div class="col text-center">
							<div class="block-27">
							    <ul>
							        <li><a href="#">&lt;</a></li>
							        <li class="active"><span>1</span></li>
		                			<li><a href="#">&gt;</a></li>
		            			</ul>
		            		</div>
		        		</div>
		    		</div>
        	</div> <!-- .col-md-8 -->
        	</div>
      	</div>
    </section> <!-- .section -->
    
{% endblock %}

templates/places.html
{% extends "base.html" %}
{% load static %}
{% block content  %}

    <div class="hero-wrap js-fullheight" style="background-image: url({% static 'images/bg_1.jpg' %});">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-center" data-scrollax-parent="true">
          <div class="col-md-9 text-center ftco-animate" data-scrollax=" properties: { translateY: '70%' }">
            <p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><span class="mr-2"><a href="{% url 'main:index' %}">Home</a></span> <span>Mashhur joylar</span></p>
            <h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">Manzillar</h1>
          </div>
        </div>
      </div>
    </div>
		

    <section class="ftco-section">
    	<div class="container">
    		<div class="row justify-content-center mb-5 pb-3">
          <div class="col-md-10 heading-section text-center ftco-animate">
            <h2 class="mb-4">Bizning yangi ta'til g'oyalarimiz</h2>
          </div>
        </div>
        <div class="row" style="display: flex; justify-content: center;">
        	<div class="col-md-5 ftco-animate align-items-center">
        		<a href="#" class="destination-entry img" style="background-image: url({% static 'images/destination-1.jpg' %});">
        			<div class="text text-center">
        				<h3>Sohil manzarasi</h3>
        			</div>
        		</a>
        	</div>
        	<div class="col-md-5 ftco-animate align-items-center">
        		<a href="#" class="destination-entry img" style="background-image: url({% static 'images/destination-3.jpg' %});">
        			<div class="text text-center">
        				<h3>Shahar manzaralari</h3>
        			</div>
        		</a>
        	</div>
        </div>
    	</div>
    </section>
		

		<section class="ftco-section">
      <div class="container">
        <div class="row" style="display: flex; justify-content:space-around;">
          <div class="col-lg-9">
          	<div class="row">
				{% for place in places %}
					<div class="col-sm col-md-6 col-lg-6 ftco-animate justify-content-center">
						<div class="destination">
							<a href="{{place.url}}" class="img img-2 d-flex justify-content-center align-items-center" style="background-image: url({{place.image.url}});">
								<div class="icon d-flex justify-content-center align-items-center">
									<span class="icon-link"></span>
								</div>
							</a>
							<div class="text p-3">
								<div class="d-flex">
									<div class="one">
										<h3><a href="#">{{place.title}}</a></h3>
										<p class="rate">
											<i class="icon-star"></i>
											<i class="icon-star"></i>
											<i class="icon-star"></i>
											<i class="icon-star"></i>
											<i class="icon-star-o"></i>
											<span>8 Rating</span>
										</p>
									</div>
									<div class="two">
										<span class="price">${{place.price}}</span>
									</div>
								</div>
								<p>{{place.body}}</p>
								<p class="days"><span>{{place.how_long}}</span></p>
								<hr>
								<p class="bottom-area d-flex">
									<span><i class="icon-map-o"></i> {{place.where}}</span> 
									<span class="ml-auto"><a href="{{place.url}}">Batafsil</a></span>
								</p>
							</div>
						</div>
					</div>
				{% endfor %}
          	</div>
          	<div class="row mt-5">
		          <div class="col text-center ">
		            <div class="block-27">
		              <ul>
		                <li><a href="#">&lt;</a></li>
		                <li class="active"><span>1</span></li>
		                <li><a href="#">&gt;</a></li>
		              </ul>
		            </div>
		          </div>
		        </div>
          </div> <!-- .col-md-8 -->
        </div>
      </div>
    </section> <!-- .section -->

{% endblock %}